### ISSUE TITLE
"godep save"  said  "is not using a known version control system"

### ISSUE THREAD

**Issue by aresetian** [tools/godep#63]
Firts at all, the version of GOLANG that I'm using is 1.2.1(go1.2.1.linux-amd64.tar.gz ).

Second,  godep was downloaded from https://github.com/kr/godep the same say of this post(09/03/2014).

My GOLANG tree is : 

$GOPATH / bin
--------------------/ godep
-------------/ pkg
-------------/ src 
--------------------/  github.com / aresetian / server /
--------------------------------------------------------------/ main.go

My problem : 

 when I write "godep save" from the place where is main.go the message on console is  : 
godep: directory "XYXYXYXYXY" is not using a known version control system
godep: error loading packages

XYXYXYXYXY : path where is $GOPATH

I have read some post;  Add a -extonly option to "godep save" #48 ,http://mmcgrana.github.io/2012/09/getting-started-with-go-on-heroku.html,  but there aren't one that can help me to solve this problem.

**Comment by TannerMoore** [comment]
Since this is still open, I thought I would explain how  fixed this issue.  For me it was because I had various text programs sitting in my $GOPATH/src folder. The error message was saying the whole src folder didn't have a known version control system, but what it meant was there were some projects within that folder that weren't being tracked by github. I pulled them out briefly and was able to successfully run godep save -r ./...

**Comment by treeder** [comment]
Why does godep expect a version control system?

**Comment by l3x** [comment]
This is a bug with godep.

This was my scenario and how I fixed it:

I was creating a new project (projectX) for my company, which did not yet have a git repo.

Note that the repo will be at github.com/company/projectX

My local dev workspace looks like this:

```bash
~/dev/go/company/src/github.com/company/projectX
```

This is what happened originally:
 
```bash
godep save
godep: directory "/Users/lex/dev/go/company/src" is not using a known version control system
godep: error loading packages
```

This is all I had to do to fix it:

```bash
cd ~/dev/go/company/src/github.com
git init
git commit
```
(Probably didn't need to run git commit)

Seems odd that I had a number of other projects, with godep working fine, in the ~/dev/go/company/src/github.com/company (ex: ~/dev/go/company/src/github.com/company/projectA, ~/dev/go/company/src/github.com/company/projectB, etc.)  prior to encountering and fixing this godep issue.

**Comment by danqing** [comment]
I agree that

    godep: directory "/Users/danqing/go/src" is not using a known version control system

is not the clearest error message in the world. It's suggesting that the entire `src` folder needs to be a git repo, whereas the issue is actually (usually) that the project itself (`go/src/github.com/danqing/project`) is not a git repo.

(The above is given that the dependencies themselves are installed via `go get`, which automatically put them under git.)

**Comment by osiloke** [comment]
I just updated godep to e28aafa1c4a9ab9108ae98211f12bbcc43e24510. This seems to spit out more useful information that actually tells you what repo isn't using a vcs.

**Comment by webfd** [comment]
I just updated godep

**Comment by gngeorgiev** [comment]
I still do not know why godep needs source control so badly?

**Comment by treeder** [comment]
Funny this issue got commented on today, I just posted this: https://medium.com/iron-io-blog/how-to-vendor-golang-dependencies-with-docker-no-git-gopath-or-godep-required-537c00da0176

**Comment by freeformz** [comment]
@gngeorgiev godep works under the assumption that all packages are in a VCS controlled repository. That repository doesn't actually have to be pushed anywhere else though.

I personally put all code into a VCS (almost always git), even if it's ever just local.

**Comment by gngeorgiev** [comment]
Yeah, I did a `git init`, this is not a problem. I am just curious why `godep` would assume this.

**Comment by viktorasm** [comment]
I'm also interested in this error message. Why should Godep care at  all if I'm using VCS? While I'm using git, apparently it's not at the level godep expects it to be. my layout is:
```
/.git
/other-stuff1
/python-service1
/python-service2
/java-service1
/node-service1
/go-services/src/project.com/Godeps/...
/go-services/src/project.com/service1
/go-services/src/project.com/service2
```
I understand that it's not very conventional layout, but I really want the whole project, which is composed of a set of microservices, to be in one repository - trying to keep personal github account down to 5 private repos.

**Comment by gngeorgiev** [comment]
@viktorasm in this case isn't it best if the inner repos are actual git repositories which are submodules of the main repo?

**Comment by viktorasm** [comment]
@gngeorgiev I really want to have one repo for the whole project. I would expect it should be up for me to decide how I want to organize the repository. My point is - why does Godep cares if I actually version-control the whole thing? What if I would be using a very unconventional VCS?.. I understand it's probably a "convention-over-configuration" thing, but missing the 'configuration" bit here, that is, telling Godep that my repo root is elsewhere.

**Comment by freeformz** [comment]
godep uses the go tooling for various bits and they mostly require the code to be in VCS, organized in certain ways.

**Comment by tchap** [comment]
Hit the same issue. Scenario:

`GOPATH` set to a Go workspace. There is `$WORKSPACE/src/modules/pkg` and when I run `godep save modules/pkg`, it tells me that `$WORKSPACE/src` is not under any known version control system. BTW `../$WORKSPACE` is a root of a Git repo, so it's not true on top of it...

**Comment by freeformz** [comment]
@tchap what version of godep do you have? If it's not `v2` or the command isn't recognized, please `go get -u github.com/tools/godep` and try again.

**Comment by tchap** [comment]
@freeformz Looks like it's `v2` and it's doing the same thing after update.

**Comment by freeformz** [comment]
@tchap can you paste the full output?

**Comment by tchap** [comment]
@freeformz Here it is. The directory mentioned as `blablabla` is the root of a git repo. I am trying to save deps for a package that is placed in `blablabla/workspace/src/modules/jira`.
```bash
$ GOPATH="$(pwd)/workspace:$GOPATH" godep save modules/jira
godep: directory "blablabla/workspace/src" is not using a known version control system
godep: error loading packages
```

**Comment by freeformz** [comment]
This works this way...

```console
$ cd <path to blablabla>/workspace/src
$ GOPATH="$(dirname $(dirname $(dirname $(pwd)))):$GOPATH" godep save
```
That above works for me in a trivial test case.

**Comment by phoet** [comment]
i'm running into the same issue with `godep: directory "/Users/peter/go/src" is not using a known version control system`.

reading the comments, i thought that there should have been an improved error-message? so i assumed that i have an old version of godep, but unfortunately there is no `godep --version` to find out. looking into the src it says `const version = 12` in version.go. which looks like it's latest.

my issue here is that i have a project in version-control, that holds multiple language directories and i just symlinked the go folder to be within the GOPATH. because of that it does not contain any `.git` directory. i could use submodules for this purpose, but i feel like it's kind of overkill for 2 or 3 files...

**Comment by jessegreathouse** [comment]
I think it's not helpful how opinionated this tool is. This is not a shot against the designers or the people who have worked hard on this project, but a of criticism of the behavior of this tool. The concept of "best" is not relevant at all -- it hinges on the false-presupposition that every project of every team is motivated by the same values. If go can compile the program, then the dependency manager should be able to track the dependencies of that program. Full stop.

**Comment by boynux** [comment]
Same here! Would be great to add a feature to skip these kind of checks. @l3x suggestion did work, but it's a bit ugly!
